web/router.ex
defmodule MiCaserito.Router do
  use MiCaserito.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MiCaserito do
    pipe_through [:browser, :browser_session] # Use the default browser stack

    get "/", PageController, :index
    get "/gps", PageController, :gps
    get "/logout", PageController, :logout
    resources "/mercados", MercadoController
  end

  scope "/auth", MiCaserito do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", MiCaserito do
  #   pipe_through :api
  # end
end

lib/mi_caserito/endpoint.ex
defmodule MiCaserito.Endpoint do
  use Phoenix.Endpoint, otp_app: :mi_caserito

  socket "/socket", MiCaserito.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :mi_caserito, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_mi_caserito_key",
    signing_salt: "IYNaJVu5"

  plug MiCaserito.Router
end

lib/mi_caserito/repo.ex
defmodule MiCaserito.Repo do
  use Ecto.Repo, otp_app: :mi_caserito
end

web/models/authorization.ex
defmodule MiCaserito.Authorization do
  use MiCaserito.Web, :model

  schema "authorizations" do
    field :provider, :string
    field :uid, :string
    field :token, :string
    field :refresh_token, :string
    field :expired_at, :integer
    belongs_to :user, MiCaserito.User

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:provider, :uid, :token, :refresh_token, :expired_at])
    |> validate_required([:provider, :uid, :token])
  end
end

web/models/mercado.ex
defmodule MiCaserito.Mercado do
  use MiCaserito.Web, :model

  schema "mercados" do
    field :nombre, :string
    field :latitud, :float
    field :longitud, :float
    field :direccion, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:nombre, :latitud, :longitud, :direccion])
    |> validate_required([:nombre, :latitud, :longitud, :direccion])
  end
end

web/models/user.ex
defmodule MiCaserito.User do
  use MiCaserito.Web, :model

  schema "users" do
    field :nombre, :string
    field :email, :string
    field :is_admin, :boolean, default: false
    has_one :authorization, MiCaserito.Authorization

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:nombre, :is_admin])
    |> validate_required([:nombre, :is_admin])
  end
end

web/controllers/auth_controller.ex
defmodule MiCaserito.AuthController do
  use MiCaserito.Web, :controller
  plug Ueberauth
  alias MiCaserito.UserFromAuth
  alias MiCaserito.User

  def request(conn, _params) do
    text conn, "Holi, no debo aparecer"
  end

  def callback(%{assigns: %{ueberauth_failure: _fails}} = conn, _params) do
    conn
    |> put_flash(:error, "Fallo en la authenticacion.")
    |> redirect(to: "/")
  end

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    case UserFromAuth.get_or_insert(auth, Repo) do
      {:ok, %User{is_admin: false} = user} ->
        conn
        |> Guardian.Plug.sign_in(user, :token, perms: %{ default: [:read]})
        |> redirect(to: page_path(conn, :index))
      {:ok, %User{is_admin: true} = user} ->
        conn
          |> Guardian.Plug.sign_in(user, :token, perms: %{ admin: [:dashboard]})
          |> redirect(to: page_path(conn, :index))
      {:error, changeset} ->
        IO.inspect changeset
        conn
        |> put_flash(:error, "Fallo en la authenticacion.")
        |> redirect(to: "/")
    end
  end

  def unauthenticated(conn, _params) do
    conn
    |> put_flash(:warning, "Logueo es necesario")
    |> redirect(to: page_path(conn, :index))
  end
end

web/controllers/mercado_controller.ex
defmodule MiCaserito.MercadoController do
  use MiCaserito.Web, :controller

  alias MiCaserito.Mercado
  use Guardian.Phoenix.Controller

  plug Guardian.Plug.EnsureAuthenticated, handler: MiCaserito.AuthController

  def index(conn, _params, _userlog, _claims) do
    mercados = Repo.all(Mercado)
    render(conn, "index.html", mercados: mercados, url: nil)
  end

  def new(conn, _params, _userlog, _claims) do
    changeset = Mercado.changeset(%Mercado{})
    render(conn, "new.html", changeset: changeset, url: nil)
  end

  def create(conn, %{"mercado" => mercado_params}, _userlog, _claims) do
    changeset = Mercado.changeset(%Mercado{}, mercado_params)

    case Repo.insert(changeset) do
      {:ok, _mercado} ->
        conn
        |> put_flash(:info, "Mercado created successfully.")
        |> redirect(to: mercado_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, url: nil)
    end
  end

  def show(conn, %{"id" => id}, _userlog, _claims) do
    mercado = Repo.get!(Mercado, id)
    render(conn, "show.html", mercado: mercado, url: nil)
  end

  def edit(conn, %{"id" => id}, _userlog, _claims) do
    mercado = Repo.get!(Mercado, id)
    changeset = Mercado.changeset(mercado)
    render(conn, "edit.html", mercado: mercado, changeset: changeset, url: nil)
  end

  def update(conn, %{"id" => id, "mercado" => mercado_params}, _userlog, _claims) do
    mercado = Repo.get!(Mercado, id)
    changeset = Mercado.changeset(mercado, mercado_params)

    case Repo.update(changeset) do
      {:ok, mercado} ->
        conn
        |> put_flash(:info, "Mercado updated successfully.")
        |> redirect(to: mercado_path(conn, :show, mercado))
      {:error, changeset} ->
        render(conn, "edit.html", mercado: mercado, changeset: changeset, url: nil)
    end
  end

  def delete(conn, %{"id" => id}, _userlog, _claims) do
    mercado = Repo.get!(Mercado, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(mercado)

    conn
    |> put_flash(:info, "Mercado deleted successfully.")
    |> redirect(to: mercado_path(conn, :index))
  end
end

web/controllers/page_controller.ex
defmodule MiCaserito.PageController do
  use MiCaserito.Web, :controller

  def index(conn, _params) do
    render conn, "index.html", url: "nill"
  end
  def gps(conn, _params) do
    render conn, "gps.html", url: "gps"
  end

  def logout(conn, _) do
	  conn
	  |> Guardian.Plug.sign_out()
	  |> put_flash(:info, "Se cerro la session exitosamente")
	  |> redirect(to: "/")
	end
end

web/views/error_view.ex
defmodule MiCaserito.ErrorView do
  use MiCaserito.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule MiCaserito.LayoutView do
  use MiCaserito.Web, :view

  def logged_in?(conn) do
    Guardian.Plug.authenticated?(conn)
  end
end

web/views/mercado_view.ex
defmodule MiCaserito.MercadoView do
  use MiCaserito.Web, :view
end

web/views/page_view.ex
defmodule MiCaserito.PageView do
  use MiCaserito.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="es-PE">
  <head>
    <meta charset="UTF-8">
    <title>MiCaserito :D</title>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="assets/imagenes/logo-ma.png">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,600,800,900,700" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>
  <body>
    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <div class="jumbotron">
          <%= if logged_in?(@conn) do %>
            <p class="lead"><%= link "Logout", to: page_path(@conn, :logout), class: "btn btn-success text-center" %></p>
          <% else %>
            <p class="lead"><%= link "Login with Facebook", to: auth_path(@conn, :request, "facebook"), class: "btn btn-success text-center" %></p>
          <% end %>
        </div>
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->

    
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <%= if @url do %>
    <script src="<%= static_path(@conn, "/js/gps.js") %>"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDcQHs_d_iHOukCURknqOC6faRpO3PTf1s&signed_in=true&callback=initMap"
        async defer>
    </script>
    <% end %>
  </body>
</html>

web/templates/mercado/edit.html.eex
<h2>Edit mercado</h2>

<%= render "form.html", changeset: @changeset,
                        action: mercado_path(@conn, :update, @mercado) %>

<%= link "Back", to: mercado_path(@conn, :index) %>

web/templates/mercado/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :nombre, class: "control-label" %>
    <%= text_input f, :nombre, class: "form-control" %>
    <%= error_tag f, :nombre %>
  </div>

  <div class="form-group">
    <%= label f, :latitud, class: "control-label" %>
    <%= number_input f, :latitud, step: "any", class: "form-control" %>
    <%= error_tag f, :latitud %>
  </div>

  <div class="form-group">
    <%= label f, :longitud, class: "control-label" %>
    <%= number_input f, :longitud, step: "any", class: "form-control" %>
    <%= error_tag f, :longitud %>
  </div>

  <div class="form-group">
    <%= label f, :direccion, class: "control-label" %>
    <%= text_input f, :direccion, class: "form-control" %>
    <%= error_tag f, :direccion %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/mercado/index.html.eex
<h2>Listing mercados</h2>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th>Direccion</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for mercado <- @mercados do %>
    <tr>
      <td><%= mercado.nombre %></td>
      <td><%= mercado.latitud %></td>
      <td><%= mercado.longitud %></td>
      <td><%= mercado.direccion %></td>

      <td class="text-right">
        <%= link "Show", to: mercado_path(@conn, :show, mercado), class: "waves-effect waves-light btn" %>
        <%= link "Edit", to: mercado_path(@conn, :edit, mercado), class: "waves-effect waves-light btn blue" %>
        <%= link "Delete", to: mercado_path(@conn, :delete, mercado), method: :delete, data: [confirm: "Are you sure?"], class: "waves-effect waves-light btn red" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New mercado", to: mercado_path(@conn, :new) %>

web/templates/mercado/new.html.eex
<h2>New mercado</h2>

<%= render "form.html", changeset: @changeset,
                        action: mercado_path(@conn, :create) %>

<%= link "Back", to: mercado_path(@conn, :index) %>

web/templates/mercado/show.html.eex
<h2>Show mercado</h2>

<ul>

  <li>
    <strong>Nombre:</strong>
    <%= @mercado.nombre %>
  </li>

  <li>
    <strong>Latitud:</strong>
    <%= @mercado.latitud %>
  </li>

  <li>
    <strong>Longitud:</strong>
    <%= @mercado.longitud %>
  </li>

  <li>
    <strong>Direccion:</strong>
    <%= @mercado.direccion %>
  </li>

</ul>

<%= link "Edit", to: mercado_path(@conn, :edit, @mercado) %>
<%= link "Back", to: mercado_path(@conn, :index) %>

web/templates/page/gps.html.eex
<h1>holi</h1>
<style>
  
  html, body {
          height: 100%;
          margin: 0;
          padding: 0;
  }
  #map {
    height: 500px;
  }
</style>
<div id="map"></div>
    

web/templates/page/index.html.eex
<nav>
      <div class="nav-wrapper"><a href="#" class="brand-logo right"><img src="assets/imagenes/logo-ma.png"></a><a href="#" data-activates="mobile-demo" class="button-collapse"><img src="assets/imagenes/menu.png" alt=""></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="bienvenido.html">Busca tu mercado</a></li>
          <li><a href="listaSelecionaDistrito.html">Ránking de Mercados</a></li>
          <li><a href="#">Tus productos</a></li>
          <li><a href="Oferta.html">Ofertas</a></li>
        </ul>
        <ul id="mobile-demo" class="side-nav">
          <li><a>Invitado<i aria-hidden="true" class="fa fa-user"></i></a></li>
          <li><a href="bienvenido.html">Busca tu mercado</a></li>
          <li><a href="listaSelecionaDistrito.html">Ránking de Mercados</a></li>
          <li><a href="#">Tus productos</a></li>
          <li><a href="Oferta.html">Ofertas</a></li>
        </ul>
      </div>
    </nav>
    <section id="bienvenido">
      <h5>¡Bienvenido a MercApp!</h5><img src="<%= static_path(@conn, "/assets/images/iconproductos.png") %>" alt="icon">
      <h6>¿Donde te encuentras?</h6><a href="#" data-activates="dropdown1" class="dropdown-button btn">Selecciona tu distrito</a>
      <ul id="dropdown1" class="dropdown-content">
        <li><a href="mapamercados.html">Lima</a></li>
      </ul><%= link "Activa mi GPS", to: page_path(@conn, :gps)%>

      
    </section>